### ISSUE TITLE
Question: "Can I stay on ETH 1.0 after the Merge?"

### ISSUE THREAD

**Issue by Lukas-Kirchbaumer** [InsideTheSim/ethmerge.com-content#24]
This question is awaiting a community contribution.

**Comment by InsideTheSim** [comment]
@Lukas-Kirchbaumer this question has been added to the site as an empty prompt. 👍

**Comment by InsideTheSim** [comment]
Answered by b7c0b1665f82934816acfeb8644984ea4addace8
