### ISSUE TITLE
Question: How does PoS security work? How does it differ from PoW?

### ISSUE THREAD

**Issue by OMGBenido** [InsideTheSim/ethmerge.com-content#28]
This question is awaiting a community contribution.

This question should be discussed in this issue. Once someone has submitted a PR that answers this question (Or the question has been added as an FAQ with no answer content) it will be linked and feedback for the answer should be given on the appropriate PR.

**Comment by InsideTheSim** [comment]
This is a great, albeit a technical question. Do you feel equipped to answer it or are you looking to have it “put on the board” for others to look at?

**Comment by OMGBenido** [comment]
I can't fully answer it (at least not in the depth that I think it should be done), but I think its really important to show that PoS is secure and Ethereum after the merge won't be a "second class" chain when it comes to security. Outlining the mechanism (slashing etc.) but also how an attack would lead to higher ETH prices that might make attacking hard would be a great addition imo.

**Comment by InsideTheSim** [comment]
@OMGBenido I feel like this has been answered via vbuterin's updates to the "Why is Ethereum (ETH) switching to Proof of Stake (Pos)?" question. 

https://github.com/InsideTheSim/ethmerge.com-content/pull/30/files?short_path=232eb93#diff-232eb937ca0547d326ef2086c6eecac9e2c7e18a09a7dec716404df2f12647aa

Thoughts?

**Comment by OMGBenido** [comment]
Dont know who the gentleman is, but I think is answer is valid 

Seriously: cant get any better than that I think. For 99% of the people this will already help. And in the end I guess thats the audience. Maybe down the road we could add something more indepth so people understand the mechanics even better. (that would be me then, cause Id really like to know how this works on a tech level)

**Comment by InsideTheSim** [comment]
You get edits by Vitalk Buterin himself, @OMGBenido - creator of Ethereum - so I agree it's probably as well written as it's going to get for now. 😂
