### ISSUE TITLE
Better Diagram for intro image

### ISSUE THREAD

**Issue by tvanepps** [InsideTheSim/ethmerge.com-content#33]
the current image suggests that PoW plays a coequal role under full proof of stake. 

Can we create a better graphic to illustrate PoW's removal in the future? is there an existing graphic I can modify?

**Comment by Myu-Unix** [comment]
Agree, it would be nice if the graphic could also put forward the fact that the current Ethereum mainnet will be part of (the greater) PoS. Kind of like "Lego bricks"

**Comment by InsideTheSim** [comment]
Hey @tvanepps, great to see you! I suppose I had not considered that PoW would be implied to stay given the "leaf" emojis used for both PoS branches, but I can certainly see that argument.

I'm open to suggestions but I myself am not much of a graphic designer to be honest. Do you know anyone in the community who way be willing to assist with design direction on a better graphic? The current one is an SVG with the emoji / text decorators placed via CSS.

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 507.83 209.65"><path d="M1169.38,510l10.29,5.91q17,9.78,33.92,19.57c2.34,1.36,2.35,1.72.07,3q-21,12.19-42.12,24.36c-.56.32-1.17.56-2.13,1-.11-1.11-.26-2-.27-2.82,0-3.59-.06-7.17,0-10.75,0-1.51-.46-2.17-2.11-2.35-2.81-3.66-153.91-2.06-172.77-1.57-5.88,6.35-76.4,73.29-82.63,79.29-7.68,7.4-16.67,12.72-27.27,14.78a71.61,71.61,0,0,1-12.4,1.25c-10.49.18-151,0-161.49.11-2.13,0-3-.59-2.92-2.83.12-5.5.13-11,0-16.49,0-2.2.84-2.65,2.79-2.64,9.58.07,149.17-.26,158.74.11,11.27.44,20.74-3.2,28.62-11.12,6.81-6.85,66.41-63.75,73.11-70.7a2.28,2.28,0,0,0,0-2.21c-7.63-7.78-65.2-65.63-73.07-73.17-6.35-6.08-14.19-8.72-23-8.65-10.5.08-153.85-.05-164.34,0-2.18,0-2.91-.62-2.85-2.84.15-5.49.1-11,0-16.49,0-1.9.56-2.68,2.57-2.66,11.49.08,155.84-.13,167.34.13,14,.32,26,5.77,36.18,15.28,5.45,5.12,10.48,10.7,15.68,16.1,4,4.14,58,58.25,63.31,60.76,4.92,2.31,170.12,1.52,175.25,1.44.42,0,1.15-1.3,1.18-2,.13-3.58.06-7.17.09-10.75C1169.16,512.23,1169.27,511.36,1169.38,510Z" transform="translate(-707.53 -432.16)"></path></svg>
```

**Comment by InsideTheSim** [comment]
![Screen Shot 2021-04-07 at 9 02 23 AM](https://user-images.githubusercontent.com/80358185/113870572-f9a65380-977f-11eb-88ec-050dce3fe6bf.jpg)

Could it be as simple as just adding more clarification to the labeling?

**Comment by tvanepps** [comment]
if I had time, I would redo [this graphic](https://twitter.com/trent_vanepps/status/1321936246332104705?s=20) to not use "Phases"

**Comment by InsideTheSim** [comment]
Love it. I’ll ask around and see if someone can help with this. If not I’ll “do it myself”.

**Comment by InsideTheSim** [comment]
If anything created could be roughly the current aspect ratio that’d be easiest for me but I’ll check out anything provided and see what I can do.

**Comment by tvanepps** [comment]
first pass here. open to any and all comments. "history" could also be "data" or "state", trying to use the simplest version

![image](https://user-images.githubusercontent.com/27454964/113941105-88d95880-97cc-11eb-9ea3-5b02853262d8.png)

**Comment by InsideTheSim** [comment]
Love the hands and the subsequent handshake emojis. 😂

completely on-brand. 

Given that we’re now keeping “proof of stake” the same for both instances maybe we can use the same 🌱 emoji?

**Comment by tvanepps** [comment]
great! i also considered including the words "Beacon Chain" in the first part, but again, don't want to introduce too many concepts

**Comment by john-Graham** [comment]
Looks great @tvanepps.   One thought... maybe make the Eth2 bar shorter, just to signify that the history doesn't go back as far as it does in Eth1.   Ether way, it looks great.

**Comment by InsideTheSim** [comment]
That’s a good idea. Additionally, I’ll be able to fade the ETH 1.0 bar to indicate it’s a continuation of a longer progression. Could also maybe (tiny) add a date for the genesis ETH 2.0 launch. 

@tvanepps - I’ll need this in SVG format and just the line work, none of the text / emojis. If that’s not something you’re able to do I can take it from here. Love the concept.

**Comment by tvanepps** [comment]
had some other comments that suggested to simplify it a bit more - the core concept is that we keep state from eth1 and the consensus from eth2

![image](https://user-images.githubusercontent.com/27454964/113943191-271aed80-97d0-11eb-94c5-32dcd9fb14de.png)

**Comment by InsideTheSim** [comment]
Given the “handshake” concept emoji is out, how about a 📄 or ⛓ emoji for ETH 1 history

**Comment by tvanepps** [comment]
Github doesn't support SVGs apparently, let me know where to send


![image](https://user-images.githubusercontent.com/27454964/113944032-db694380-97d1-11eb-8ed0-8e9f0f4d7adb.png)

**Comment by InsideTheSim** [comment]
@tvanepps if you can open the SVG in a text editor (such as VS Code) and copy/paste the file contents here in a codeblock I can work with that. 👍

**Comment by tvanepps** [comment]
I didn't know this was a thing!

`<svg width="971" height="529" viewBox="0 0 971 529" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0)">
<path d="M290.358 107L291.417 105.938C291.136 105.658 290.755 105.5 290.358 105.5V107ZM-14 107H-15.5C-15.5 107.828 -14.8284 108.5 -14 108.5V107ZM450.796 267.1L449.737 268.162L449.737 268.162L450.796 267.1ZM736 282H737.5C737.5 281.172 736.828 280.5 736 280.5V282ZM736 335H734.5C734.5 335.532 734.781 336.023 735.239 336.293C735.698 336.562 736.264 336.569 736.729 336.311L736 335ZM924 230.5L924.729 231.811C925.205 231.546 925.5 231.045 925.5 230.5C925.5 229.955 925.205 229.454 924.729 229.189L924 230.5ZM736 126L736.729 124.689C736.264 124.431 735.698 124.438 735.239 124.707C734.781 124.977 734.5 125.468 734.5 126H736ZM736 180V181.5C736.828 181.5 737.5 180.828 737.5 180H736ZM507.914 180L506.854 181.062C507.136 181.342 507.517 181.5 507.914 181.5V180ZM347.475 19.8995L348.535 18.8378L348.535 18.8377L347.475 19.8995ZM-14 5V3.5C-14.8284 3.5 -15.5 4.17157 -15.5 5H-14ZM290.358 105.5H286.899V108.5H290.358V105.5ZM279.982 105.5H273.064V108.5H279.982V105.5ZM266.147 105.5H259.23V108.5H266.147V105.5ZM252.313 105.5H245.396V108.5H252.313V105.5ZM238.478 105.5H231.561V108.5H238.478V105.5ZM224.644 105.5H217.727V108.5H224.644V105.5ZM210.81 105.5H203.892V108.5H210.81V105.5ZM196.975 105.5H190.058V108.5H196.975V105.5ZM183.141 105.5H176.223V108.5H183.141V105.5ZM169.306 105.5H162.389V108.5H169.306V105.5ZM155.472 105.5H148.555V108.5H155.472V105.5ZM141.637 105.5H134.72V108.5H141.637V105.5ZM127.803 105.5H120.886V108.5H127.803V105.5ZM113.968 105.5H107.051V108.5H113.968V105.5ZM100.134 105.5H93.2168V108.5H100.134V105.5ZM86.2996 105.5H79.3824V108.5H86.2996V105.5ZM72.4652 105.5H65.5479V108.5H72.4652V105.5ZM58.6307 105.5H51.7135V108.5H58.6307V105.5ZM44.7963 105.5H37.8791V108.5H44.7963V105.5ZM30.9618 105.5H24.0447V108.5H30.9618V105.5ZM17.1274 105.5H10.2102V108.5H17.1274V105.5ZM3.29302 105.5H-3.62417V108.5H3.29302V105.5ZM-10.5414 105.5H-14V108.5H-10.5414V105.5ZM-12.5 107V103.357H-15.5V107H-12.5ZM-12.5 96.0714V88.7857H-15.5V96.0714H-12.5ZM-12.5 81.5V74.2143H-15.5V81.5H-12.5ZM-12.5 66.9286V59.6429H-15.5V66.9286H-12.5ZM-12.5 52.3571V45.0714H-15.5V52.3571H-12.5ZM-12.5 37.7857V30.5H-15.5V37.7857H-12.5ZM-12.5 23.2143V15.9286H-15.5V23.2143H-12.5ZM-12.5 8.64287V5H-15.5V8.64287H-12.5ZM-14 6.5H-10.4625V3.5H-14V6.5ZM-3.38747 6.5H3.68755V3.5H-3.38747V6.5ZM10.7626 6.5H17.8376V3.5H10.7626V6.5ZM24.9126 6.5H31.9876V3.5H24.9126V6.5ZM39.0626 6.5H46.1377V3.5H39.0626V6.5ZM53.2127 6.5H60.2877V3.5H53.2127V6.5ZM67.3627 6.5H74.4377V3.5H67.3627V6.5ZM81.5128 6.5H88.5878V3.5H81.5128V6.5ZM95.6628 6.5H102.738V3.5H95.6628V6.5ZM109.813 6.5H116.888V3.5H109.813V6.5ZM123.963 6.5H131.038V3.5H123.963V6.5ZM138.113 6.5H145.188V3.5H138.113V6.5ZM152.263 6.5H159.338V3.5H152.263V6.5ZM166.413 6.5H173.488V3.5H166.413V6.5ZM180.563 6.5H187.638V3.5H180.563V6.5ZM194.713 6.5H201.788V3.5H194.713V6.5ZM208.863 6.5H215.938V3.5H208.863V6.5ZM223.013 6.5H230.088V3.5H223.013V6.5ZM237.163 6.5H244.238V3.5H237.163V6.5ZM251.313 6.5H258.388V3.5H251.313V6.5ZM265.463 6.5H272.538V3.5H265.463V6.5ZM279.613 6.5H286.688V3.5H279.613V6.5ZM293.763 6.5H300.838V3.5H293.763V6.5ZM307.913 6.5H311.451V3.5H307.913V6.5ZM311.451 6.5C312.533 6.5 313.611 6.53542 314.684 6.60563L314.88 3.61203C313.742 3.53757 312.598 3.5 311.451 3.5V6.5ZM321.095 7.44838C323.216 7.86966 325.302 8.42862 327.342 9.11994L328.305 6.27874C326.142 5.54555 323.929 4.9527 321.68 4.50588L321.095 7.44838ZM333.317 11.5913C335.249 12.5425 337.12 13.6206 338.919 14.8203L340.584 12.3246C338.676 11.0521 336.691 9.90862 334.642 8.89983L333.317 11.5913ZM344.052 18.7521C344.862 19.4604 345.65 20.197 346.416 20.9613L348.535 18.8377C347.723 18.0272 346.886 17.246 346.028 16.4947L344.052 18.7521ZM346.416 20.9613L348.923 23.4629L351.042 21.3393L348.535 18.8378L346.416 20.9613ZM353.936 28.466L358.95 33.4692L361.069 31.3456L356.055 26.3425L353.936 28.466ZM363.964 38.4723L368.977 43.4754L371.096 41.3519L366.083 36.3487L363.964 38.4723ZM373.991 48.4786L379.005 53.4817L381.124 51.3582L376.11 46.355L373.991 48.4786ZM384.019 58.4849L389.032 63.488L391.151 61.3644L386.138 56.3613L384.019 58.4849ZM394.046 68.4911L399.06 73.4943L401.179 71.3707L396.165 66.3676L394.046 68.4911ZM404.073 78.4974L409.087 83.5006L411.206 81.377L406.192 76.3739L404.073 78.4974ZM414.101 88.5037L419.114 93.5068L421.234 91.3833L416.22 86.3801L414.101 88.5037ZM424.128 98.51L429.142 103.513L431.261 101.39L426.247 96.3864L424.128 98.51ZM434.156 108.516L439.169 113.519L441.288 111.396L436.275 106.393L434.156 108.516ZM444.183 118.523L449.197 123.526L451.316 121.402L446.302 116.399L444.183 118.523ZM454.21 128.529L459.224 133.532L461.343 131.408L456.329 126.405L454.21 128.529ZM464.238 138.535L469.252 143.538L471.371 141.415L466.357 136.412L464.238 138.535ZM474.265 148.541L479.279 153.544L481.398 151.421L476.384 146.418L474.265 148.541ZM484.293 158.548L489.306 163.551L491.425 161.427L486.412 156.424L484.293 158.548ZM494.32 168.554L499.334 173.557L501.453 171.433L496.439 166.43L494.32 168.554ZM504.347 178.56L506.854 181.062L508.973 178.938L506.467 176.437L504.347 178.56ZM507.914 181.5H511.478V178.5H507.914V181.5ZM518.605 181.5H525.733V178.5H518.605V181.5ZM532.861 181.5H539.988V178.5H532.861V181.5ZM547.116 181.5H554.244V178.5H547.116V181.5ZM561.372 181.5H568.499V178.5H561.372V181.5ZM575.627 181.5H582.755V178.5H575.627V181.5ZM589.882 181.5H597.01V178.5H589.882V181.5ZM604.138 181.5H611.265V178.5H604.138V181.5ZM618.393 181.5H625.521V178.5H618.393V181.5ZM632.649 181.5H639.776V178.5H632.649V181.5ZM646.904 181.5H654.032V178.5H646.904V181.5ZM661.159 181.5H668.287V178.5H661.159V181.5ZM675.415 181.5H682.542V178.5H675.415V181.5ZM689.67 181.5H696.798V178.5H689.67V181.5ZM703.925 181.5H711.053V178.5H703.925V181.5ZM718.181 181.5H725.308V178.5H718.181V181.5ZM732.436 181.5H736V178.5H732.436V181.5ZM737.5 180V176.625H734.5V180H737.5ZM737.5 169.875V163.125H734.5V169.875H737.5ZM737.5 156.375V149.625H734.5V156.375H737.5ZM737.5 142.875V136.125H734.5V142.875H737.5ZM737.5 129.375V126H734.5V129.375H737.5ZM735.271 127.311L738.405 129.053L739.862 126.431L736.729 124.689L735.271 127.311ZM744.671 132.536L750.938 136.019L752.395 133.397L746.129 129.914L744.671 132.536ZM757.205 139.503L763.471 142.986L764.929 140.364L758.662 136.881L757.205 139.503ZM769.738 146.469L776.005 149.953L777.462 147.331L771.195 143.847L769.738 146.469ZM782.271 153.436L788.538 156.919L789.995 154.297L783.729 150.814L782.271 153.436ZM794.805 160.403L801.071 163.886L802.529 161.264L796.262 157.781L794.805 160.403ZM807.338 167.369L813.605 170.853L815.062 168.231L808.795 164.747L807.338 167.369ZM819.871 174.336L826.138 177.819L827.595 175.197L821.329 171.714L819.871 174.336ZM832.405 181.303L838.671 184.786L840.129 182.164L833.862 178.681L832.405 181.303ZM844.938 188.269L851.205 191.753L852.662 189.131L846.395 185.647L844.938 188.269ZM857.471 195.236L863.738 198.719L865.195 196.097L858.929 192.614L857.471 195.236ZM870.005 202.203L876.271 205.686L877.729 203.064L871.462 199.581L870.005 202.203ZM882.538 209.169L888.805 212.653L890.262 210.031L883.995 206.547L882.538 209.169ZM895.071 216.136L901.338 219.619L902.795 216.997L896.529 213.514L895.071 216.136ZM907.605 223.103L913.871 226.586L915.329 223.964L909.062 220.481L907.605 223.103ZM920.138 230.069L923.271 231.811L924.729 229.189L921.595 227.447L920.138 230.069ZM923.271 229.189L920.138 230.931L921.595 233.553L924.729 231.811L923.271 229.189ZM913.871 234.414L907.605 237.897L909.062 240.519L915.329 237.036L913.871 234.414ZM901.338 241.381L895.071 244.864L896.529 247.486L902.795 244.003L901.338 241.381ZM888.805 248.347L882.538 251.831L883.995 254.453L890.262 250.969L888.805 248.347ZM876.271 255.314L870.005 258.797L871.462 261.419L877.729 257.936L876.271 255.314ZM863.738 262.281L857.471 265.764L858.929 268.386L865.195 264.903L863.738 262.281ZM851.205 269.247L844.938 272.731L846.395 275.353L852.662 271.869L851.205 269.247ZM838.671 276.214L832.405 279.697L833.862 282.319L840.129 278.836L838.671 276.214ZM826.138 283.181L819.871 286.664L821.329 289.286L827.595 285.803L826.138 283.181ZM813.605 290.147L807.338 293.631L808.795 296.253L815.062 292.769L813.605 290.147ZM801.071 297.114L794.805 300.597L796.262 303.219L802.529 299.736L801.071 297.114ZM788.538 304.081L782.271 307.564L783.729 310.186L789.995 306.703L788.538 304.081ZM776.005 311.047L769.738 314.531L771.195 317.153L777.462 313.669L776.005 311.047ZM763.471 318.014L757.205 321.497L758.662 324.119L764.929 320.636L763.471 318.014ZM750.938 324.981L744.671 328.464L746.129 331.086L752.395 327.603L750.938 324.981ZM738.405 331.947L735.271 333.689L736.729 336.311L739.862 334.569L738.405 331.947ZM737.5 335V331.688H734.5V335H737.5ZM737.5 325.062V318.438H734.5V325.062H737.5ZM737.5 311.812V305.188H734.5V311.812H737.5ZM737.5 298.562V291.938H734.5V298.562H737.5ZM737.5 285.312V282H734.5V285.312H737.5ZM736 280.5H732.539V283.5H736V280.5ZM725.618 280.5H718.696V283.5H725.618V280.5ZM711.774 280.5H704.853V283.5H711.774V280.5ZM697.931 280.5H691.009V283.5H697.931V280.5ZM684.088 280.5H677.166V283.5H684.088V280.5ZM670.244 280.5H663.323V283.5H670.244V280.5ZM656.401 280.5H649.479V283.5H656.401V280.5ZM642.558 280.5H635.636V283.5H642.558V280.5ZM628.714 280.5H621.793V283.5H628.714V280.5ZM614.871 280.5H607.949V283.5H614.871V280.5ZM601.028 280.5H594.106V283.5H601.028V280.5ZM587.184 280.5H580.263V283.5H587.184V280.5ZM573.341 280.5H566.42V283.5H573.341V280.5ZM559.498 280.5H552.576V283.5H559.498V280.5ZM545.655 280.5H538.733V283.5H545.655V280.5ZM531.811 280.5H524.89V283.5H531.811V280.5ZM517.968 280.5H511.046V283.5H517.968V280.5ZM504.125 280.5H497.203V283.5H504.125V280.5ZM490.281 280.5H486.821V283.5H490.281V280.5ZM486.821 280.5C485.739 280.5 484.66 280.465 483.587 280.394L483.391 283.388C484.529 283.462 485.673 283.5 486.821 283.5V280.5ZM477.176 279.552C475.056 279.13 472.969 278.571 470.93 277.88L469.967 280.721C472.13 281.454 474.343 282.047 476.592 282.494L477.176 279.552ZM464.955 275.409C463.023 274.458 461.151 273.379 459.352 272.18L457.688 274.675C459.595 275.948 461.58 277.091 463.629 278.1L464.955 275.409ZM454.219 268.248C453.41 267.54 452.622 266.803 451.856 266.039L449.737 268.162C450.549 268.973 451.385 269.754 452.243 270.505L454.219 268.248ZM451.856 266.039L449.349 263.537L447.23 265.661L449.737 268.162L451.856 266.039ZM444.335 258.534L439.321 253.531L437.202 255.654L442.216 260.658L444.335 258.534ZM434.308 248.528L429.294 243.525L427.175 245.648L432.189 250.651L434.308 248.528ZM424.28 238.521L419.267 233.518L417.148 235.642L422.161 240.645L424.28 238.521ZM414.253 228.515L409.239 223.512L407.12 225.636L412.134 230.639L414.253 228.515ZM404.225 218.509L399.212 213.506L397.093 215.629L402.106 220.632L404.225 218.509ZM394.198 208.503L389.184 203.499L387.065 205.623L392.079 210.626L394.198 208.503ZM384.171 198.496L379.157 193.493L377.038 195.617L382.052 200.62L384.171 198.496ZM374.143 188.49L369.13 183.487L367.01 185.61L372.024 190.614L374.143 188.49ZM364.116 178.484L359.102 173.481L356.983 175.604L361.997 180.607L364.116 178.484ZM354.088 168.477L349.075 163.474L346.956 165.598L351.969 170.601L354.088 168.477ZM344.061 158.471L339.047 153.468L336.928 155.592L341.942 160.595L344.061 158.471ZM334.034 148.465L329.02 143.462L326.901 145.585L331.914 150.588L334.034 148.465ZM324.006 138.459L318.992 133.456L316.873 135.579L321.887 140.582L324.006 138.459ZM313.979 128.452L308.965 123.449L306.846 125.573L311.86 130.576L313.979 128.452ZM303.951 118.446L298.938 113.443L296.819 115.567L301.832 120.57L303.951 118.446ZM293.924 108.44L291.417 105.938L289.298 108.062L291.805 110.563L293.924 108.44Z" fill="black"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M762 253.5H520.487L335.986 436.198C331.586 440.556 325.644 443 319.451 443H87V396H309.784L494.285 213.302C498.686 208.944 504.628 206.5 510.821 206.5H762V172L869 231.5L762 291V253.5Z" fill="black"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M295.717 95H-14V48H305.451C311.683 48 317.661 50.4759 322.068 54.883L442.568 175.383L409.334 208.617L295.717 95Z" fill="black"/>
</g>
<defs>
<clipPath id="clip0">
<rect width="971" height="529" fill="white"/>
</clipPath>
</defs>
</svg>
`

**Comment by InsideTheSim** [comment]
@tvanepps it's been integrated! Thanks for the great feedback and art-direction.
https://ethmerge.com/
