### ISSUE TITLE
Question: Where do the fees paid to miners go to after the merge?

### ISSUE THREAD

**Issue by uberchar** [InsideTheSim/ethmerge.com-content#34]
This question is awaiting a community contribution.

This question should be discussed in this issue. Once someone has submitted a PR that answers this question (Or the question has been added as an FAQ with no answer content) it will be linked and feedback for the answer should be given on the appropriate PR.

**Comment by InsideTheSim** [comment]
I've added this question to the list - it will show as awaiting community response. Thanks!
