### ISSUE TITLE
Question: "When is the merge happening?"

### ISSUE THREAD

**Issue by InsideTheSim** [InsideTheSim/ethmerge.com-content#4]
This question is awaiting a community contribution.

**Comment by InsideTheSim** [comment]
Closed via #15

**Comment by SwagtimusPrime** [comment]
I'd add that there's very strong community consensus to get the merge done ASAP.

Something like: 

>As of time of writing there's no definitive date for the merge; however there is now strong community consensus to prioritize the merge over other upgrades after the London hard fork.

**Comment by InsideTheSim** [comment]
Hey @SwagtimusPrime! Great to see you! Would you be willing to submit a PR with the update as you see fit? I'd love to grow the list of contributors on this repo to encourage others to contribute as well.

**Comment by InsideTheSim** [comment]
@SwagtimusPrime bonus points if you have a good article to source for the evidence of community support for the merge happening quickly.

**Comment by SwagtimusPrime** [comment]
> @SwagtimusPrime bonus points if you have a good article to source for the evidence of community support for the merge happening quickly.

I'll get to it!

**Comment by Myu-Unix** [comment]
From https://hackmd.io/@timbeiko/acd-update-001 (Shanghai part)

> Alternatively, there is an increased desire from the community to focus on the consensus (eth2)- and application (eth1)-layer merge, or, simple The Merge :tm:.

**Comment by InsideTheSim** [comment]
Updates have been made that address this, going to close this one for now. Thanks!
