### ISSUE TITLE
Discussion of <Question: Can I stay on "Ethereum 1.0" after "The Merge"?>

### ISSUE THREAD

**Issue by marceljay** [InsideTheSim/ethmerge.com-content#52]
> No — as it will functionally cease to exist. When "The Merge" occurs the entire Eth 1.0 proof-of-work (PoW) chain becomes the state of the Eth 2.0 proof-of-stake (PoS) chain.

The merge is a hard fork like any other and depends on adoption. In my opinion, especially in The-Merge case, there is a non-zero chance of two future co-existing networks just like Ethereum / Eth Classic today. So I would argue saying that Eth1 will "cease to exist" is just wrong, even though it can be stated that it's the goal and shared vision most aspire.

**Comment by InsideTheSim** [comment]
Hey @marceljay - the answer could be expanded to explain the ice age, the unforkable nature of DeFi due to fiat-backed stable coins, etc. But in my opinion the ultimate conclusion is correct. PoW Ethereum will cease to exist.
